name: cypress test
on: workflow_dispatch
jobs:
  cypress-run:
    name: Run Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./cypress/node_modules
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Run Test
        uses: cypress-io/github-action@v6
        with:
          install: true
          browser: chrome
          working-directory: ./
          command: npm run test
